repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^contents/slides/gyromorphs-21-09-2026/slides\.html$'
      - id: end-of-file-fixer
        exclude: '^contents/slides/gyromorphs-21-09-2026/slides\.html$'
      - id: check-added-large-files
        exclude: '^contents/slides/gyromorphs-21-09-2026/slides\.html$'
        args: [--maxkb=2000]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: '^contents/slides/gyromorphs-21-09-2026/slides\.html$'
        additional_dependencies:
          - tomli
        args:
          - --ignore-words-list=astroid
          - --ignore-regex=\b(NWO|shadowIn|bufferIn|detailIn)\b
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
