project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "contents/**/*.qmd"
  resources:
    - contents/slides/gyromorphs-21-09-2026/slides.html
    - google71bbe46973ffb153.html
    - publickey.asc
    - contents/slides/pintofscience-19-05-2026/slides/animations/
    - contents/slides/pintofscience-19-05-2026/slides/figures/

website:
  title: "Isidora Araya Day"
  site-url: "https://isidora.araya.day/"
  image: contents/images/profile.jpg
  open-graph: true
  twitter-card: true
  favicon: favicon.svg
  navbar:
    left:
      - contents/research.qmd
    right:
      - contents/letschat.qmd
    search: true
  page-navigation: true
  page-footer:
    center:
      - text: "📧 isidora@araya.day"
        href: mailto:isidora@araya.day
      - text: "Get my GPG key"
        href: publickey.asc
    right: "Made with [Quarto](https://quarto.org) and [GitHub Copilot](https://github.com/features/copilot)"

format:
  html:
    theme:
      - minty
      - theme.scss
    page-layout: full
    css: styles.css
    include-in-header: contents/_view-transition.html
    # toc: true

execute:
  freeze: auto
