
::: {.hero-section}

Hi!👋 I am **Isidora Araya Day**, a theoretical condensed matter physicist working on **mesoscopic superconductivity, topology, and quantum transport**.

📍 Currently I am a postdoc at DIPC in San Sebastián, Spain, working with [Adolfo Grushin](https://grushingroup.cnrs.fr/).

💻 I completed my PhD in the [Quantum Tinkerer group](http://quantumtinkerer.group/) at TU Delft, The Netherlands, with [Anton Akhmerov](https://antonakhmerov.org/) and [Michael Wimmer](https://michaelwimmer.org/), and defended in February 2026.

I love working on problems that require combining analytics and numerics.
One of my favorite projects so far was developing **Pymablock**, an open-source Python package to do quantum mechanical perturbation theory efficiently, numerically and symbolically.

::: {.project-links}
[📖 Documentation](https://pymablock.readthedocs.io/){.btn .btn-primary}
[💻 GitHub Repository](https://github.com/quantum-tinkerer/pymablock){.btn .btn-outline-primary}
:::

Check out my [research page](contents/research.html) to learn more!

### My journey so far


:::

::: {.trajectory-section data-scroll-reveal="true"}

{{< trajectory-stepper >}}
:::



::: {.quarto-footer}
I made this with [Quarto](https://quarto.org) and [Github Copilot](https://github.com/features/copilot).
:::
